name: Package
on: workflow_dispatch
jobs:
    build-win-pyinstaller:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
                python-version: '3.11'
          - name: Install Requirements and PyInstaller
            run: 'pip install -r requirements.txt pyinstaller'
          - name: Build application with PyInstaller
            run: 'pyinstaller -yF -n vintagestory-modmgr.exe __main__.py'
            env:
                PYTHONOPTIMIZE: 2
          - name: Test application
            run: 'dist/vintagestory-modmgr.exe --help'
          - name: Upload Build Artifact
            uses: actions/upload-artifact@v3
            with:
                name: vintagestory-modmgr.exe
                path: dist/vintagestory-modmgr.exe
    build-zipapp:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
                python-version: '3.11'
          - name: Add Files to ZIP
            run: 'zip -r -0 vintagestory-modmgr.zip __main__.py basemod.py gui/'
          - name: Convert ZIP to PYZ
            run: 'python3 -m zipapp -p /usr/bin/python3 vintagestory-modmgr.zip -o vintagestory-modmgr.pyz'
          - name: Test application
            run: 'python3 vintagestory-modmgr.pyz --help'
          - name: Upload Build Artifact
            uses: actions/upload-artifact@v3
            with:
                name: vintagestory-modmgr.pyz
                path: vintagestory-modmgr.pyz
